#!C:\Users\prana\Desktop\VoiceForge TTV Pipeine\VoiceForge--Forge-Character-Voices-from-Pure-Text\voiceforge-env\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
